import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./reset.css";
import "./globals.css";
import Header from "@/components/header";

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
